import type { Metadata } from "next";
import { Be_Vietnam_Pro } from 'next/font/google'
import "./globals.css";
// import { ThemeProvider } from "./component/theme-provider";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

 
const poppins = Be_Vietnam_Pro({
  weight: ['100','200','300','400', '500', '600', '700','800','900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${poppins.className}  w-full`}
      >
          <header>
            <Navbar/>
          </header>
          <main>
            {children}
            </main>
          <footer>
            <Footer/>
          </footer>
      </body>
    </html>
  );
}
